# Generated by Django 2.1 on 2018-11-23 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(choices=[('FY2018-19', 'FY2018-19'), ('FY2019-20', 'FY2019-20')], max_length=10)),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('event_type', models.CharField(choices=[('FIXED', 'FIXED'), ('OPTIONAL', 'OPTIONAL')], max_length=50)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=50)),
                ('tenure_month', models.IntegerField(default=0)),
                ('applied_on', models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 23, 11, 47, 55, 317323), null=True)),
                ('leave_type', models.CharField(max_length=50)),
                ('leave_start', models.DateField()),
                ('leave_end', models.DateField()),
                ('leave_for', models.CharField(max_length=10)),
                ('days', models.FloatField(default=0)),
                ('reason', models.CharField(max_length=100, null=True)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('DELETED', 'DELETED'), ('CANCELLED', 'CANCELLED')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('empid', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=50)),
                ('financial_year', models.CharField(choices=[('FY2018-19', 'FY2018-19'), ('FY2019-20', 'FY2019-20')], max_length=10)),
                ('single_day_entitlement', models.FloatField(default=0)),
                ('single_day_availed', models.FloatField(default=0)),
                ('single_day_balance', models.FloatField(default=0)),
                ('annual_entitlement', models.FloatField(default=0)),
                ('annual_availed', models.FloatField(default=0)),
                ('annual_balance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveCategory',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('single_day_entitlement', models.FloatField(default=0)),
                ('annual_entitlement', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveReason',
            fields=[
                ('leave_reason', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
