# Generated by Django 2.1 on 2018-11-23 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyleave', '0002_auto_20181123_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 11, 55, 9, 172538), null=True),
        ),
    ]
