# Generated by Django 2.1 on 2018-11-23 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyleave', '0005_auto_20181123_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 12, 17, 34, 350776), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='empid',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
