# Generated by Django 2.1 on 2018-11-23 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyleave', '0014_auto_20181123_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='status',
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 13, 58, 3, 638505), null=True),
        ),
    ]
