# Generated by Django 2.1 on 2018-11-23 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyleave', '0018_auto_20181123_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='status',
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 14, 7, 28, 656907), null=True),
        ),
    ]
