# Generated by Django 2.1 on 2018-11-23 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyleave', '0020_auto_20181123_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 15, 46, 19, 726220), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='days',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
