# Generated by Django 2.1 on 2018-11-23 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyleave', '0021_auto_20181123_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 16, 8, 36, 75910), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='days',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
