# Generated by Django 2.1 on 2018-11-26 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyleave', '0022_auto_20181123_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_app_id',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 11, 0, 47, 405890), null=True),
        ),
    ]
