# Generated by Django 2.1 on 2018-11-26 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyleave', '0025_auto_20181126_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='leave_app_id',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='id',
            field=models.IntegerField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 11, 54, 34, 366732), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='empid',
            field=models.CharField(max_length=10),
        ),
    ]
