# Generated by Django 2.1 on 2018-11-27 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyleave', '0028_auto_20181126_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplicationdetails',
            name='transid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 27, 15, 49, 56, 405818), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplicationdetails',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 27, 15, 49, 56, 406818), null=True),
        ),
    ]
