# Generated by Django 2.1 on 2018-11-30 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyleave', '0029_auto_20181127_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(choices=[('FY2018-19', 'FY2018-19'), ('FY2019-20', 'FY2019-20')], max_length=10)),
                ('empid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=50)),
                ('leave_type', models.CharField(choices=[('Single Day', 'Single Day'), ('Annual', 'Annual')], max_length=50)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('credited', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('availed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('lop', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 30, 12, 15, 46, 712458), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplicationdetails',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 30, 12, 15, 46, 712458), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplicationdetails',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED')], max_length=50, null=True),
        ),
    ]
