# Generated by Django 2.1 on 2018-12-11 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyleave', '0031_auto_20181203_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOPRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=50)),
                ('month', models.DateField(blank=True, null=True)),
                ('lop', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='fy',
            name='id',
        ),
        migrations.AlterField(
            model_name='fy',
            name='financial_year',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 15, 4, 21, 940843), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplicationdetails',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 11, 15, 4, 21, 941843), null=True),
        ),
    ]
