# Generated by Django 2.1 on 2018-12-14 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyleave', '0033_auto_20181214_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 14, 15, 2, 29, 883012), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_for',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='leaveapplicationdetails',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 14, 15, 2, 29, 883012), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplicationdetails',
            name='leave_for',
            field=models.CharField(max_length=20),
        ),
    ]
