# Generated by Django 2.1.5 on 2019-01-17 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyleave', '0036_auto_20190115_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='category',
            field=models.CharField(choices=[('UNPAID', 'UNPAID'), ('PAID', 'PAID'), ('EO PAID', 'EO PAID')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='paid_leave',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='status_update_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='status_update_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 17, 11, 1, 15, 354007), null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='unpaid_leave',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 11, 1, 15, 353007), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplicationdetails',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 11, 1, 15, 354007), null=True),
        ),
    ]
