# Generated by Django 2.1.5 on 2019-01-17 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyleave', '0037_auto_20190117_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 11, 4, 19, 904563), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='status_update_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplicationdetails',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 11, 4, 19, 905563), null=True),
        ),
    ]
