# Generated by Django 2.1.5 on 2019-01-17 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyleave', '0038_auto_20190117_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveregister',
            old_name='availed',
            new_name='al_availed',
        ),
        migrations.RenameField(
            model_name='leaveregister',
            old_name='closing_balance',
            new_name='al_closing_balance',
        ),
        migrations.RenameField(
            model_name='leaveregister',
            old_name='credited',
            new_name='al_credited',
        ),
        migrations.RenameField(
            model_name='leaveregister',
            old_name='opening_balance',
            new_name='al_opening_balance',
        ),
        migrations.RemoveField(
            model_name='leaveregister',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='leaveregister',
            name='lop',
        ),
        migrations.AddField(
            model_name='leaveregister',
            name='sdl_availed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='leaveregister',
            name='sdl_credited',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='leaveregister',
            name='sdl_opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='leaveregister',
            name='sld_closing_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 11, 51, 27, 722305), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplicationdetails',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 11, 51, 27, 722305), null=True),
        ),
    ]
