# Generated by Django 2.1.5 on 2019-01-17 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyleave', '0040_auto_20190117_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveregister',
            old_name='sld_closing_balance',
            new_name='sdl_closing_balance',
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 14, 16, 56, 421558), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplicationdetails',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 14, 16, 56, 422558), null=True),
        ),
    ]
