# Generated by Django 2.1.5 on 2019-01-17 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyleave', '0042_auto_20190117_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 16, 13, 47, 510569), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplicationdetails',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 16, 13, 47, 511569), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplicationdetails',
            name='days',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lopregister',
            name='lop',
            field=models.FloatField(default=0),
        ),
    ]
