# Generated by Django 2.1.5 on 2019-01-19 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyleave', '0043_auto_20190117_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='manager_remarks',
            field=models.CharField(blank=True, help_text='Maximum Limit is 200 Characters', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lopregister',
            name='leaveid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 19, 15, 22, 34, 787738), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='comments',
            field=models.CharField(blank=True, help_text='Maximum Limit is 200 Characters', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplicationdetails',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 19, 15, 22, 34, 789738), null=True),
        ),
    ]
