# Generated by Django 2.1.5 on 2019-01-19 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyleave', '0044_auto_20190119_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 19, 20, 19, 3, 566103), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='category',
            field=models.CharField(choices=[('Choose...', 'Choose...'), ('UNPAID', 'UNPAID'), ('PAID', 'PAID'), ('EO PAID', 'EO PAID')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('Choose...', 'Choose...'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplicationdetails',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 19, 20, 19, 3, 568103), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplicationdetails',
            name='status',
            field=models.CharField(choices=[('Choose...', 'Choose...'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], max_length=50, null=True),
        ),
    ]
