# Generated by Django 2.1.5 on 2019-01-19 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyleave', '0045_auto_20190119_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lopregister',
            old_name='month',
            new_name='leave_month',
        ),
        migrations.AddField(
            model_name='lopregister',
            name='leave_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 19, 20, 46, 3, 61733), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplicationdetails',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 19, 20, 46, 3, 62733), null=True),
        ),
    ]
