# Generated by Django 4.1.4 on 2023-05-23 02:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyleave', '0050_auto_20210524_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 23, 8, 17, 24, 138001), null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplicationdetails',
            name='applied_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 23, 8, 17, 24, 138001), null=True),
        ),
    ]
