# Generated by Django 2.1 on 2018-10-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('empid', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=75, unique=True)),
                ('company', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField(null=True)),
                ('work_location', models.CharField(choices=[('Goa', 'Goa'), ('Gurugram', 'Gurugram'), ('New Delhi', 'New Delhi'), ('Mumbai', 'Mumbai'), ('Pune', 'Pune')], max_length=100)),
                ('employee_setup', models.CharField(choices=[('Employee', 'Employee'), ('Professional', 'Professional'), ('Intern', 'Intern')], max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=20)),
                ('user_type', models.CharField(choices=[('User', 'User'), ('Manager', 'Manager'), ('HR', 'HR'), ('Admin', 'Admin')], default='User', max_length=20)),
                ('weekend_day', models.IntegerField(choices=[(1, 1), (2, 2)], default=2)),
                ('leave_category', models.CharField(max_length=10)),
                ('single_day_entitlement', models.CharField(default=0, max_length=5)),
                ('annual_entitlement', models.CharField(default=0, max_length=5)),
                ('reporting_manager_empid', models.CharField(max_length=10)),
                ('reporting_manager_name', models.CharField(max_length=100)),
                ('reporting_manager_email', models.EmailField(max_length=75)),
                ('date_of_leaving', models.DateField(blank=True, null=True)),
                ('employee_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
            ],
        ),
    ]
