# Generated by Django 2.1 on 2018-11-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employeestatus_employmentsetup_gender_maritalstatus_usertype_weekendday_worklocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekendday',
            name='weekend_day',
            field=models.IntegerField(),
        ),
    ]
