# Generated by Django 2.1 on 2018-11-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20181114_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='weekend_day',
            field=models.CharField(choices=[(1, 1), (2, 2)], default=2, max_length=2),
        ),
    ]
