# Generated by Django 2.1 on 2018-11-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20181114_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='employment_setup',
            field=models.CharField(choices=[('Employment', 'Employment'), ('Professional', 'Professional'), ('Intern', 'Intern')], max_length=50),
        ),
    ]
