# Generated by Django 2.1 on 2018-11-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auto_20181114_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklocation',
            name='work_location',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
