# Generated by Django 2.1 on 2018-11-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20181115_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklocation',
            name='work_location',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
