# Generated by Django 2.1 on 2018-11-15 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_auto_20181115_0937'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkLocation',
            new_name='WorkLocation2',
        ),
    ]
