# Generated by Django 2.1 on 2018-11-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20181115_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_location', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WorkLocation2',
        ),
    ]
