# Generated by Django 2.1 on 2018-11-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='employee_status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='employment_setup',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='marital_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='user_type',
            field=models.CharField(default='User', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='weekend_day',
            field=models.CharField(default=2, max_length=2),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='work_location',
            field=models.CharField(max_length=100),
        ),
    ]
