# Generated by Django 2.1 on 2018-11-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_auto_20181115_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetails',
            old_name='work_location',
            new_name='job_location',
        ),
    ]
