# Generated by Django 2.1 on 2018-11-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_auto_20181115_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='job_location',
        ),
    ]
