# Generated by Django 2.1 on 2018-11-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_auto_20181115_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkLocation',
        ),
        migrations.RemoveField(
            model_name='location',
            name='id',
        ),
        migrations.AlterField(
            model_name='location',
            name='job_location',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
