# Generated by Django 2.1 on 2018-11-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_auto_20181116_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='employee_status',
            field=models.CharField(default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='job_location',
            field=models.CharField(default='Goa', max_length=100),
        ),
    ]
